routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PostController::class, 'index']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::resource('posts', PostController::class);

Route::get('user/edit', [UserController::class, 'edit'])->name('user.edit');

Route::get('user/profile', [UserController::class, 'profile'])->name('user.profile');

Route::put('user', [UserController::class, 'update'])->name('user.update');

require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Post extends Model
{
    use HasFactory, InteractsWithMedia;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'alt',
        'img',
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['show', 'index']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        $posts = DB::table('posts')->simplePaginate(3);

        return view('posts.index')->with('posts', $posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function store(Request $request): RedirectResponse
    {
        Validator::make($request->all(), [
            'title'     => 'required|string',
            'alt'       => 'required|string',
            'img'       => 'file|image'
        ])->validate();

        $post = new Post;
        $post->title = $request->title;
        $post->alt = $request->alt;

        $file_name = hash('sha256', time()).'.'.$request->img->extension();
        $request->img->move(storage_path('app\public\images'), $file_name);

        $post->img = $file_name;

        $user = Auth::user();

        $user->posts()->save($post);

        return redirect()->route('user.profile')->with('success','Post created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param Post $post
     * @return Application|Factory|View|Response
     */
    public function show(Post $post)
    {
        return view('posts.show')->with('post', $post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Post $post
     * @return Application|Factory|View|RedirectResponse
     */
    public function edit(Post $post)
    {
        if(Auth::user()->id != $post->user_id){
            return redirect()->route('posts.index')->with('error','You have no rights to edit this post');
        }
        return view('posts.edit')->with('post', $post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Post $post
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function update(Request $request, Post $post)
    {
        Validator::make($request->all(), [
            'title'     => 'required|string',
            'alt'       => 'required|string',
            'img'       => 'file|image'
        ])->validate();

        $post->title = $request->title;
        $post->alt = $request->alt;

        if($request->hasFile('img')){
            $old_img = $post->img;

            $file_name = hash('sha256', time()).'.'.$request->img->extension();
            $request->img->move(storage_path('app\public\images'), $file_name);
            $post->img = $file_name;

            Storage::delete(storage_path('app\public\images'. $old_img));
        }

        $post->save();

        return redirect()->route('user.profile')->with('success','Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Post $post
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(Post $post): RedirectResponse
    {
        if(Auth::user()->id != $post->user_id){
            return redirect()->route('posts.index')->with('error','You have no rights to delete this post');
        }

        Storage::delete(public_path('images'. $post->img));
        $post->delete();

        return redirect()->back()->with('success','Post deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/posts/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Post') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('posts.store') }}" enctype="multipart/form-data" method="POST">
                        @csrf

                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label for="title"><strong>Title:</strong></label>
                                    <input type="text" name="title" class="form-control" placeholder="Enter Title"><br>
                                    <label for="alt"><strong>Alt:</strong></label>
                                    <input type="text" name="alt" class="form-control" placeholder="Enter Alt"><br>
                                    <label for="img"><strong>Choose Image:</strong></label>
                                    <input id="img" type="file" name="img" class="form-control"><br>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a class="btn btn-primary" href="{{ url()->previous() }}">Cancel</a>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/posts/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Post') }}
        </h2>
    </x-slot>


    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('posts.update',$post->id) }}" enctype="multipart/form-data" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label for="image"><strong>Title:</strong></label>
                                    <input type="text" name="title" value="{{ $post->title }}" class="form-control" placeholder="Title"><br>
                                    <label for="image"><strong>Alt:</strong></label>
                                    <input type="text" name="alt" value="{{ $post->alt }}" class="form-control" placeholder="Alt"><br>
                                    <label for="img"><strong>Choose Image:</strong></label>
                                    <input id="img" type="file" name="img" class="form-control"><br>
                                    <label for="image"><strong>Image:</strong></label><br>
                                    <img src="{{asset('storage/images') . '/' .  $post->img}}" alt="{{ $post->alt }}">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a class="btn btn-primary" href="{{ url()->previous() }}">Cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/posts/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Posts') }}
            @auth
                <a class="btn btn-success ml-1" href="{{ route('posts.create') }}">New Post</a>
            @endif
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @elseif($message = Session::get('error'))
                <div class="alert alert-danger">
                    <p>{{ $message }}</p>
                </div>
            @endif

            @foreach ($posts as $key => $post)
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg mb-3">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="row" style="margin-bottom: 2rem;">
                        <div class="col-xs-6 col-sm-6 col-md-6">
                            <img style="width: 100%;" src="{{asset('storage/images') . '/' .  $post->img}}" alt="{{ $post->alt }}">
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6">
                            <p><strong>Title:</strong> {{ $post->title }}</p><br>
                            <p><strong>Alt:</strong> {{ $post->alt }}</p><br>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
            {!! $posts->links(); !!}
        </div>
    </div>
</x-app-layout>

resources/views/posts/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Show Post') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="row">
                        <div class="col-xs-6 col-sm-6 col-md-6">
                            <img style="width: 100%;" src="{{asset('storage/images') . '/' .  $post->img}}" alt="{{ $post->alt }}">
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6">
                            <p><strong>Title:</strong> {{ $post->title }}</p><br>
                            <p><strong>Alt:</strong> {{ $post->alt }}</p><br>
                            <a class="btn btn-primary" href="{{ url()->previous() }}">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>